### ISSUE TITLE
Returning a reference of a sent message

### ISSUE THREAD

**Issue by PaulAsjes** [slackhq/node-slack-client#163] opened 2016-03-06 18:01 UTC
So in the pre-v2 days you could do something like this:

```
let sentMessage = channel.send(`Hello!`);

setTimeout(() => {
  sentMessage.updateMessage('I will be deleted in 2 seconds.');
}, 1000);

setTimeout(() => {
  sentMessage.deleteMessage();
}, 3000);
```

Nowadays the callback for `rtm.sendMessage` only returns an error object and no other arguments. 

I had a look through the source and found that although you can update messages via `channel.updateMessage`, you need a reference to the message you sent, in particular its timestamp value. Plus it seems that you can only retrieve messages by using `channel.getMessageByTs`, again requiring that pesky timestamp.

Is there a way in the current system to emulate the above behavior? If not is it perhaps an idea to add a reference to the sent message in `rtm.sendMessage`'s optional callback like so:

```
rtm.sendMessage(`Hello!`, channel.id, (err, msg) => {
  channel.updateMessage('Updated!', msg.id);
});
```

Happy to implement this myself is someone can point me in the right direction.

**Comment by Everesty** [comment] 2016-03-06 22:31
So, I did a little research into it, and i found some good information that would help with this: messages always have unique time stamps (versus ids, which I don't think they have at all in the same sense that a channel has an id), and [that time stamp is sent back via RTM api](https://api.slack.com/rtm#sending_messages).

The issue with this is that you have to wait for the RTM client to receive the ok from the server to know what that timestamp is. The callback (and message id) should be held until that ok comes back.

Also, I found, in my search, that there was [a `TODO` for this exact functionality](https://github.com/slackhq/node-slack-client/blob/master/lib/clients/rtm/client.js#L409). @l12s the [slack api](https://api.slack.com/rtm#sending_messages) doesn't indicate that a type is given in responses to RTM messages, so is that a bug in this module or is it an oversight in the api docs?

As for now, it seems that the RTM client will emit a `CLIENT_EVENTS.RTM.MESSAGE` event whenever a message that is sent is recieved. Listen to that event and check for a "reply_to" field. That'll be the id that the client generated to be assigned to that message. How you'll make all of this knowledge work together, I don't know.

**Comment by l12s** [comment] 2016-03-06 23:08
Looking at this now.

**Comment by l12s** [comment] 2016-03-06 23:20
Ok, thanks for that context @Everesty - I think I understand what the issue is.

So, two possible scenarios you'll want to have a message callback trigger on:

### Fail
the websocket send fails, callback is called with the error object and a null response

### Success
the message succeeds and the websocket (quickly, but async from the send acknowledgement on the client socket) replies with a message that looks like:

```json
{
	"reply_to": 1,
	"type": "message",
	"channel": "C0CHZA86Q",
	"user": "U0CJ5PC7L",
	"text": "test",
	"ts": "1457305861.000002"
}
```

The failure case is currently handled, with the `optCb` function from sendMessage passed through. However, it's also treating the successful send of the message as equivalent to the success case.

So, I'm going to do two things:
- add promise support to sendMessage + send, as a I forgot to when I added it to the web API
- track any callback that's passed through and call it with the message object from the success case when that returns

**Comment by PaulAsjes** [comment] 2016-03-06 23:30
:+1: Exactly what I was hoping for, thanks!

**Comment by l12s** [comment] 2016-03-07 00:33
Ok, the above PR should fix this for you. I'd appreciate some :eyes: on it if you have a moment to check it out.

I'll add a couple tests for the new behavior too.

**Closed** 2016-03-08 07:06 UTC
