### ISSUE TITLE
WebSocket closed silently and will not reconnect

### ISSUE THREAD

**Issue by compulim** [slackhq/node-slack-client#53] opened 2015-06-29 01:52 UTC
Sometimes Slack RTM WebSocket connection close silently after running for a few days (2-3 days in our 2-3 months experiences). It does not emit any errors, unhandled exceptions, or quitting the app.

The existing "reconnect" algorithm only reconnect on auth error. Therefore, the app does not know the WS connection is dropped. It simply receive no new messages until someone restarted the app.

Currently, our remedy looks like this:
```
var slack = new (require('slack-client'))('xoxb-...', true, true);

slack
    …
    .on('close', function () {
        console.log('Connection closed, retrying');
        slack.reconnect();
    })
    …
    .login();
```

I would suggest putting this logic back into `client.coffee` when `autoReconnect` is enabled. Or building a more robust watchdog.

**Comment by IgorAntun** [comment] 2015-07-10 17:39
[+1]

Oh, good (somehow) to know I'm not the only one with this. I have the exact same issue, usually every 2~3 days the app will just disconnect without sending any notice or exceptions or anything. Thanks for your 'remedy', I'll implement it until it gets fixed for good :)

**Comment by ccoenen** [comment] 2015-07-13 06:57
possible duplicate of https://github.com/slackhq/node-slack-client/issues/5 - which has been unanswered for over a year :-(

**Comment by vanm** [comment] 2015-07-13 16:26
In my testing, this proposed reconnect on `close` can result in multiple (duplicate) open websocket connections over time.  Seems like we need to dive in on the root cause of these "silent" websocket close events or make a more robust reconnect method.  Interested what other people find after trying this approach over a few days, too - for me, it always results in duplicate websockets after a few days.

**Comment by shepelt** [comment] 2015-07-14 06:07
@vanm the same behavior was observed for me as well.
I tried slack.login() on close event as well, which resulted in the same behavior (multiple websocket created)
I believe the reconnect mechanism is not implemented properly at the moment.

**Comment by vanm** [comment] 2015-07-18 17:55
I started debugging by using a forked version of this library that logs the error code + message from websocket close events.  See PR #61 

The websocket error code I'm seeing for these silent connection closed events is `1000`, which maps to "normal" in the ws npm.  I was hoping for a more descriptive error code (for example, there are "going away" or "protocol error" codes), but I think the "normal" error code backs up how widespread this is and why it doesn't trigger any error handlers.

**Comment by shepelt** [comment] 2015-07-19 18:31
@vanm I think the root cause of this issue lies in the fact that there is no coping mechanism for connection closed events.
According to the current implementation, node-slack client is not supposed to reconnect for any kind of closed event.

https://github.com/slackhq/node-slack-client/blob/master/src/client.coffee#L127-130
```javascript
@ws.on 'close', =
    @emit 'close'
    @connected = false
    @socketUrl = null
```

The same is true for error event.
https://github.com/slackhq/node-slack-client/blob/master/src/client.coffee#L123-125
```javascript
@ws.on 'error', (error)=>
    # TODO: Reconnect?
    @emit 'error', error
````

Node-slack-client reconnect is triggered by ping-pong mechanism only.
https://github.com/slackhq/node-slack-client/blob/master/src/client.coffee#L111-115
```javascript
if @_lastPong? and Date.now() - @_lastPong > 10000
        @logger.error "Last pong is too old: %d", (Date.now() - @_lastPong) / 1000
        @authenticated = false
        @connected = false
        @reconnect()
````

**Comment by vanm** [comment] 2015-07-19 19:02
Right, I was mainly logging the error code for added context to the "closed silently" claim - I think the error codes back that up that there are no errors or specific websocket issues - it's just Slack closing the connection cleanly (for whatever reason).  I figured we'd tackle the "Reconnect doesn't work" claim in the other ticket #5 - but I agree with you, reconnect on close / error should be something this library handles.

**Comment by compulim** [comment] 2015-08-09 22:28
@vanm I am wondering why calling `reconnect()` would result in multiple WS connections. As in [client.coffee:160](https://github.com/slackhq/node-slack-client/blob/master/src/client.coffee#L160), calling `reconnect()` will kill previously opened WS connection before opening a new one (and also ping-pong).

@shepelt You should call `reconnect()` instead of `login()` after connection close.

**Comment by vanm** [comment] 2015-08-10 19:00
@compulim Because the websocket `close` event emits a new `close` event on the Slack client itself.

https://github.com/slackhq/node-slack-client/blob/master/src/client.coffee#L128

If you are calling `reconnect` in the slack client close handler, you are going to be calling websocket close again.  

Now, if the websocket was actually terminated, there isn't an issue, because the readyState is 3 (CLOSED) and the .close() operation will be a no-op (there is a guard clause in the WS library).  No harm done and no subsequent websocket close or slack close events.

However, if the websocket is still open, as it is in the case of "Last Pong too old" scenario, this will result in the current websocket being closed in multiple reconnects being called almost simultaneously.
1. The reconnect triggered by the "last pong too old" will trigger a websocket close that in turn calls reconnect again, resulting in a `login()` call.
2. The reconnect triggered by the "last pong too old" continues after that websocket close, calling `login()`.

These simultaneous logins are the issue.  I think the slack client `close` event should be independent / not be relied upon to have the information necessary to trigger a reconnect and everything related to reconnect should be handled within the slack client itself.

Check out https://github.com/slackhq/node-slack-client/pull/66 and let me know what you think.

**Comment by l12s** [comment] 2016-02-13 20:34
Ok, first off, I apologize for how long it's taken us to resolve this issue.

I just pushed the 2.0.0 release for this library, which is a ground up refactor with the aim of building a lib that both Slack and our external contributors can easily work with and improve.

It also includes substantially improved reconnection logic and handling, for both routine disconnects as well `team_migration` events and similar. I'll also be making sure to expedite fixes for any issues with reconnection logic in particular, as I know that's been a pain for folks in the past.

So, I'd suggest that the best way to resolve these issues is to upgrade to the latest version. If you have any problems in doing that, please create a new issue and I'll try and help you in there.

**Closed by l12s** 2016-02-13 20:34 UTC
